/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppr;

import javax.swing.JOptionPane;

/**
 *
 * @author vdunz
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PiPRCTXT = new javax.swing.JLabel();
        PPRCorpTXT = new javax.swing.JLabel();
        NdoCartaoTXT = new javax.swing.JLabel();
        NdoCartaoField = new javax.swing.JTextField();
        LoginTXT = new javax.swing.JLabel();
        SenhaLoginTXT = new javax.swing.JLabel();
        SenhaLoginField = new javax.swing.JPasswordField();
        GerenteTXT = new javax.swing.JLabel();
        IDTXT = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        SenhaGerenteTXT = new javax.swing.JLabel();
        SenhaGerenteField = new javax.swing.JPasswordField();
        copyrightTXT = new javax.swing.JLabel();
        entrarGerenteButton = new javax.swing.JButton();
        entrarLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        PiPRCTXT.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        PiPRCTXT.setText("Payments in Pennys Refunding Corporation");

        PPRCorpTXT.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        PPRCorpTXT.setText("PPR Corp.");

        NdoCartaoTXT.setText("Numero do Cartão: ");

        NdoCartaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NdoCartaoFieldActionPerformed(evt);
            }
        });

        LoginTXT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LoginTXT.setText("Login");

        SenhaLoginTXT.setText("Senha: ");

        GerenteTXT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        GerenteTXT.setText("Gerente");

        IDTXT.setText("ID: ");

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        SenhaGerenteTXT.setText("Senha: ");

        copyrightTXT.setText("© 2018 Payments in Pennys Refunding Corporation All Rights Reserved");

        entrarGerenteButton.setText("ENTRAR");

        entrarLoginButton.setText("ENTRAR");
        entrarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NdoCartaoTXT)
                            .addComponent(SenhaLoginTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SenhaLoginField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(NdoCartaoField))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhaGerenteTXT)
                            .addComponent(IDTXT))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(SenhaGerenteField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(LoginTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GerenteTXT)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(PiPRCTXT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(PPRCorpTXT)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(copyrightTXT)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(entrarLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrarGerenteButton)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PiPRCTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPRCorpTXT)
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginTXT)
                    .addComponent(GerenteTXT))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NdoCartaoTXT)
                    .addComponent(NdoCartaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDTXT)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaLoginTXT)
                    .addComponent(SenhaLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SenhaGerenteTXT)
                    .addComponent(SenhaGerenteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrarGerenteButton)
                    .addComponent(entrarLoginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(copyrightTXT)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NdoCartaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NdoCartaoFieldActionPerformed
        
    }//GEN-LAST:event_NdoCartaoFieldActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void entrarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarLoginButtonActionPerformed
        String idCartao = NdoCartaoTXT.getText();
        try{
            long conta =  Long.parseLong(idCartao);
            BancoDAO banco = new BancoDAO();
            if(!banco.buscaCliente(conta)){ // Gerar mensagem de erro
                JOptionPane.showMessageDialog(null, "A conta nÃ£o existe", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else{ //ir para a janela de conta do cliente
                InterfaceGrafica ig = new InterfaceGrafica();
                ig.setVisible( true );
                this.dispose();
            }
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Digite um valor inteiro para conta", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarLoginButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GerenteTXT;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDTXT;
    private javax.swing.JLabel LoginTXT;
    private javax.swing.JTextField NdoCartaoField;
    private javax.swing.JLabel NdoCartaoTXT;
    private javax.swing.JLabel PPRCorpTXT;
    private javax.swing.JLabel PiPRCTXT;
    private javax.swing.JPasswordField SenhaGerenteField;
    private javax.swing.JLabel SenhaGerenteTXT;
    private javax.swing.JPasswordField SenhaLoginField;
    private javax.swing.JLabel SenhaLoginTXT;
    private javax.swing.JLabel copyrightTXT;
    private javax.swing.JButton entrarGerenteButton;
    private javax.swing.JButton entrarLoginButton;
    // End of variables declaration//GEN-END:variables
}
